[versions]
aboutlibraries = "14.0.0-b02"
activity-compose = "1.12.4"
core-splashscreen = "1.2.0"
datastore-preferences = "1.2.0"
gradle = "9.0.1"
hilt = "2.59.2"
kotlin = "2.3.10"
ksp = "2.3.6"
lottie = "6.7.1"
material3 = "1.4.0"
oneui-design = "0.9.1+oneui8"
oneui-icons = "1.1.0"

[libraries]
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
oneui-design = { module = "io.github.tribalfs:oneui-design", version.ref = "oneui-design" }
oneui-icons = { module = "io.github.oneuiproject:icons", version.ref = "oneui-icons" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
android-application = { id = "com.android.application", version.ref = "gradle" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
oneui = ["oneui-icons", "oneui-design"]
